FROM alpine:3.6

RUN apk add --no-cache perl perl-dev curl wget make gcc g++
RUN curl -sL --compressed https://git.io/cpm > cpm && chmod +x ./cpm
RUN ./cpm install -v -g App::FatPacker::Simple

RUN mkdir /work
WORKDIR /work
